### PR TITLE
Don't round annotation start and end times

### LINKED ISSUE #313: Setting of end and start times of annotation are not accurate
When altering the length of an annotation with a duration using the start and end buttons the new start or end of an annotation is not perfectly accurate. It is slightly earlier or later than the actual position of the playhead (see screencast: https://tube.switch.ch/channels/9a280238).

### LINKED ISSUE #318: Annotations are not placed on the exact position of the playhead
Annotations are inserted on the nearest second and not on the exact playback time. This means that the desired playback time is not displayed when selecting the annotation. See tube.switch.ch/videos/fef0e56b

### PR DESCRIPTION
**Pull request by JulianKniephoff**
* Fixes #318 
* Fixes #313

### CODE REVIEW

**Comment by dagraf** [comment]
And what about https://github.com/opencast/annotation-tool/issues/313? Does this pull request also fix this issue?

**Comment by JulianKniephoff** [comment]
@dagraf I don't think so unfortunately. :frowning_face:

**Comment by JulianKniephoff** [comment]
Now it does. :wink:

**Comment by dagraf** [comment]
FANTASTIC!! :)

**Comment by JulianKniephoff** [comment]
Since @rrolf probably doesn't have time for these reviews in the near future anyway, I will go ahead and merge some of these that have been approved by @luniki and/or @Arnei.

**Pull request merged**
