### PR TITLE
Set color and background color as inline style in the timeline

### LINKED ISSUE #427: Bern features: Annotation of categories belongig to a series have no color in "daughter tracks"
If I create a category belonging to a series in video A and then in video B click on a label of this category, the inserted annotation has NO color on the track (meaning = is grey). In the list of annotations the annotation has the correct color. Using the same category in video A (where it got created) does not lead to such missing coloring on the track.

Solution: Please make sure that annotations always are correctly colored regardless of which video the category was created in. 

Screenshot: Categories E3 and S3 were created in this video and their annotations are correctly colored on the track. Categories S1 and S2 were created in other videos of the same series and their annotations are grey instead of orange or yellow.
Bildschirmfoto 2020-12-10 um 13 11 38

### PR DESCRIPTION
**Pull request by JulianKniephoff**
This is probably slightly less efficient, but makes some upcoming
changes simpler. Also the stylesheet solution was a bit janky to begin
with, and we should probably touch that code again in the long run
anyway.

This should fix #427 when integrated in #414.

### CODE REVIEW

**Review by Arnei — COMMENTED** [review]
Seems to solve the intended issue, great.

Also makes annotations in the timeline not immediately change their color anymore, when the color of their category changes. Likely related to #425.

**Comment by JulianKniephoff** [comment]
Right, that was actually one of the advantages of the stylesheet approach. :thinking: 

I guess I could just adapt what I did for #435. Let me see ...

**Comment by JulianKniephoff** [comment]
Note that this now uses #437, which should probably reviewed first.

**Review by Arnei — APPROVED** [review]
Approving this by virtue of being unable to break it.

**Pull request merged**
