### PR TITLE
Simplify the bundle plugin instructions

### PR DESCRIPTION
**Pull request by JulianKniephoff**
This fixes the following warning about unused `Improt-Packages` in Maven:

```
[INFO] ------< org.opencast.annotate:annotation-tool-frontend-delivery >-------
[INFO] Building Opencast Annotation Tool :: Backend :: Frontend Delivery 0-SNAPSHOT [6/7]
[INFO] -------------------------------[ bundle ]-------------------------------
[...]
[INFO] --- maven-bundle-plugin:3.5.0:bundle (default-bundle) @ annotation-tool-frontend-delivery ---
[WARNING] Bundle org.opencast.annotate:annotation-tool-frontend-delivery:bundle:0-SNAPSHOT : Unused Import-Package instructions: [org.opencastproject.*]
```

I also used the opportunity to remove some (by now) redundant explicit version specifications.

### CODE REVIEW

**Comment by Arnei** [comment]
Does remove the warning, but also breaks my local OC 8.3 AllInOne.

Probably relevant part of the logs:
```
2021-05-03 09:18:49,008 | WARN  | (Util$OsgiLogger:205) - Error while starting bundle: file:/home/arnewilken/IdeaProjects/opencast/build/opencast-dist-develop-8.3/deploy/annotation-tool-impl-0-SNAPSHOT.jar
org.osgi.framework.BundleException: Unable to resolve annotation-tool-impl [65](R 65.5): missing requirement [annotation-tool-impl [65](R 65.5)] osgi.wiring.package; (&(osgi.wiring.package=javax.ws.rs)(version>=1.1.0)(!(version>=2.0.0))) Unresolved requirements: [[annotation-tool-impl [65](R 65.5)] osgi.wiring.package; (&(osgi.wiring.package=javax.ws.rs)(version>=1.1.0)(!(version>=2.0.0)))]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4149) ~[?:?]
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2119) ~[?:?]
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998) ~[?:?]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260) [8:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233) [8:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startAllBundles(DirectoryWatcher.java:1221) [8:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:515) [8:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) [8:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316) [8:org.apache.felix.fileinstall:3.6.4]
2021-05-03 09:18:50,013 | INFO  | (Activator:43) - Stopped annotation tool
2021-05-03 09:18:50,055 | WARN  | (Util$OsgiLogger:205) - Error while starting bundle: file:/home/arnewilken/IdeaProjects/opencast/build/opencast-dist-develop-8.3/deploy/annotation-tool-impl-0-SNAPSHOT.jar
org.osgi.framework.BundleException: Unable to resolve annotation-tool-impl [65](R 65.5): missing requirement [annotation-tool-impl [65](R 65.5)] osgi.wiring.package; (&(osgi.wiring.package=javax.ws.rs)(version>=1.1.0)(!(version>=2.0.0))) Unresolved requirements: [[annotation-tool-impl [65](R 65.5)] osgi.wiring.package; (&(osgi.wiring.package=javax.ws.rs)(version>=1.1.0)(!(version>=2.0.0)))]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4149) ~[?:?]
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2119) ~[?:?]
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998) ~[?:?]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260) [8:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233) [8:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startAllBundles(DirectoryWatcher.java:1221) [8:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:515) [8:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) [8:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316) [8:org.apache.felix.fileinstall:3.6.4]
2021-05-03 09:18:50,059 | INFO  | (Activator:38) - Starting annotation tool
2021-05-03 09:18:50,784 | WARN  | (ServletController:182) - Can't find the request for http://localhost:8080/admin-ng/event/events.json's Observer 
```

**Comment by JulianKniephoff** [comment]
Interesting. :thinking: Can you tryi n 9? That worked for me. If it's that, we can just wait a couple more weeks before merging this, since 8 support ends with the release of 10. :sweat_smile:

**Comment by Arnei** [comment]
You're right, 9 is fine. RIP my beautiful OC 8.3 that I solely used for annotation-tool.

**Review by Arnei — APPROVED** [review]

**Comment by JulianKniephoff** [comment]
I mean you can still spend some time with it June 15th. ^_^

**Comment by JulianKniephoff** [comment]
Opencast 8 is "deprecated" now, but there was a conflict with #499. @Arnei can you double check this for me when you get the chance? :)

**Comment by Arnei** [comment]
> Opencast 8 is "deprecated" now, but there was a conflict with #499. @Arnei can you double check this for me when you get the chance? :)

I did not get a conflict with #499.

**Pull request merged**
