### PR TITLE
Update to Opencast 9/10

### PR DESCRIPTION
**Pull request by JulianKniephoff**
This also requires us to migrate away from
the `SimpleServicePublisher`.
I used that opportunity to convert the project to using
OSGi annotations instead of the more error prone XML based
service declarations.

---

**Note**: This includes #501 so that I could test this stuff effectively.

### CODE REVIEW

**Comment by Arnei** [comment]
I'm running into the below error when trying to load an event with the annotation tool.
```
XHR PUT http://localhost:8080/extended-annotations/users [HTTP/1.1 405 Method Not Allowed 0ms]
```
Running Opencast 10 on CentOS. I'm fairly certain I set up permissions correctly.

**Comment by JulianKniephoff** [comment]
Do you see anything interesting in the logs? :thinking: Can you just send me everything that's in the logs after you installed the tool?

**Comment by Arnei** [comment]
Tried again and it works now. I suppose I made some mistake yesterday.

**Comment by JulianKniephoff** [comment]
Yeah no, it's weird. I had something similar happen at first, but then it magically worked. I noticed this behavior a few times before, too, though, when switching Opencast versions or branches or something like that. I **still** don't know what causes this. :shrug:

**Pull request merged**
