### PR TITLE
Stop deleted tracks from reappearing when a new track is created in the same session

### LINKED ISSUE #164: Once deleted track show up when creating a new track in the same session
If a track gets deleted and in the same session a new track is created the once deleted track shows up again and is kind auf a ghost-track: It can not be deleted or altered in any ways. When reloading the whole page the deleted track disappears.

Bug replicated in Edge and Firefox.

Video which shows the Bug (in Swiss German, but I'll guess you'll get the point anyway): https://www.screencast.com/t/A8hXCpmMz2tb

### PR DESCRIPTION
**Pull request by JulianKniephoff**
Fixes #164.

NB to the reviewer: When you test this, you might get confused by #264, which is already fixed in #265.

### CODE REVIEW

**Comment by rrolf** [comment]
If I delete a track, only the first annotation within the track is removed immedeately. If there is only one annotation in the track the track is also removed. 
Otherwise the track is only removed after reload.

**Comment by JulianKniephoff** [comment]
@rrolf I **think** it should be fixed now.

**Comment by dagraf** [comment]
Nope, it is not yet fixed.

**Comment by dagraf** [comment]
Yep, is fixed. Thx!

**Pull request merged**
