### PR TITLE
New track visibility option "Shared with admin"

### LINKED ISSUE #11: New track visibility option "Shared with admin"
Originally reported by: **Rüdiger Rolf (Bitbucket: [rrolf](https://bitbucket.org/rrolf), GitHub: [rrolf](https://github.com/rrolf))**

----------------------------------------

Additional to private and public tracks also an additional visibility option should be added, where the track is viewable for the person who created the track and all users with the ACL action "annotation-admin".

----------------------------------------
- Bitbucket: https://bitbucket.org/opencast-community/annotation-tool/issue/11

### PR DESCRIPTION
**Pull request by JulianKniephoff**
Finally! This should close #11.

### CODE REVIEW

**Comment by JulianKniephoff** [comment]
This should also close #10, right? :thinking:

**Comment by rrolf** [comment]
I get build errors:

```
Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.815 sec - in org.opencast.annotation.endpoint.ExtendedAnnotationsRestServiceTest
Running org.opencast.annotation.impl.ExtendedAnnotationServiceJpaImplTest
Tests run: 31, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.891 sec <<< FAILURE! - in org.opencast.annotation.impl.ExtendedAnnotationServiceJpaImplTest
testTrack(org.opencast.annotation.impl.ExtendedAnnotationServiceJpaImplTest)  Time elapsed: 0.111 sec  <<< FAILURE!
java.lang.AssertionError: expected:<3> but was:<0>
	at org.opencast.annotation.impl.ExtendedAnnotationServiceJpaImplTest.testTrack(ExtendedAnnotationServiceJpaImplTest.java:244)

Running org.opencast.annotation.impl.JsonsTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.opencast.annotation.impl.JsonsTest

Results :

Failed tests: 
  ExtendedAnnotationServiceJpaImplTest.testTrack:244 expected:<3> but was:<0>

Tests run: 45, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] opencast-annotation ................................ SUCCESS [  1.191 s]
[INFO] annotation-tool-frontend ........................... SUCCESS [  5.938 s]
[INFO] opencast-annotation-api ............................ SUCCESS [  1.906 s]
[INFO] opencast-annotation-impl ........................... FAILURE [ 10.027 s]
[INFO] opencast-annotation-tool ........................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 19.310 s
[INFO] Finished at: 2018-01-19T11:38:48+01:00
[INFO] Final Memory: 55M/624M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project opencast-annotation-impl: There are test failures.
[ERROR] 
[ERROR] Please refer to /opencast/annotations/pr80/opencast-backend/annotation-impl/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :opencast-annotation-impl
```

**Comment by JulianKniephoff** [comment]
I saw these test failures at some point and fixed them. Maybe I forgot to push those changes. (They were part of a rebase.)

I rebased again just now to accomodate the already merged PRs and it works on my side, so it should include the necessary changes. Can you maybe test it again? x)

**Comment by JulianKniephoff** [comment]
Note that this should be merged after #80 and has to be reviewed first; there might have been new references to `annotationsTool` added.

**Comment by rrolf** [comment]
And also here we have merge conflicts

**Comment by JulianKniephoff** [comment]
Okay, that took some doing but it should be properly rebased now.

**Pull request merged**
