### PR TITLE
Removed last vestiges of "annotations-tool" terminology

### PR DESCRIPTION
**Pull request by JulianKniephoff**
I took the freedom to rename all the remaining things called `annotations-tool` (and variations of that) to `annotation-tool` (and the corresponding variation of that ...). For the lazy readers (which includes me): The difference between the two is the plural s.

This PR does nothing else but I would still like to have a second pair of eyes on it, because it is so big.

### CODE REVIEW

**Comment by JulianKniephoff** [comment]
Should be fixed. :)

**Comment by rrolf** [comment]
This still (or again? as I just merged pr77) has merge conflicts.

**Comment by JulianKniephoff** [comment]
Again. ;) #77 and #81 both introduced changes involving the global `annotationsTool` object which this PR renames (among other things), so it needs to be updated for both of them (or the other way around, depending on the merge order). I would say we merge before this one now, too, so this PR only needs to be updated once.

I will leave the merge conflicts in this one until then to remind me; we are lucky that there are some, it might as well just have silently failed. :wink:

**Comment by JulianKniephoff** [comment]
Fixed the merge conflicts and also changed all the newly introduced references to `annotationsTool` by #77 and #81.

**Pull request merged**
