### PR TITLE
Improve the project structure slightly

### PR DESCRIPTION
**Pull request by JulianKniephoff**
The main thing this PR does is getting rid of the artificial `frontend-delivery` project/bundle/thing. The `frontend/pom.xml` now directly bundles the results of the Grunt build.

As usual, some minor nitpicks I found while doing this are included.

Note that this makes it a bit simpler to hack just the frontend again. Once you have an Opencast instance with a running Annotation Tool, you merely need to rebuild and redeploy the `frontend` bundle, instead of building `frontend` and then building and deploying `frontend-delivery` (or just building and deploying the entire project again, which is more convenient but also takes longer).

### CODE REVIEW

**Comment by Arnei** [comment]
There are a couple of "TODO" comments in there, are those intended?

**Comment by JulianKniephoff** [comment]
Whops. Nope, those are just for me to ponder another time. Should be gone now. :sweat_smile:

**Review by Arnei — APPROVED** [review]
Works in my local installation and seems reasonable as far as I can tell

**Comment by JulianKniephoff** [comment]
Fixed CI; this should not change anything about @Arnei's review, so I'm merging this now.

**Pull request merged**
